use ControleMedicamentosTrabalho

SELECT * FROM TBPACIENTE
SELECT * FROM TBFORNECEDOR
SELECT * FROM TBFUNCIONARIO
SELECT * FROM TBMEDICAMENTO
SELECT * FROM TBREQUISICAO

DELETE FROM TBPACIENTE
DELETE FROM TBFORNECEDOR
DELETE FROM TBFUNCIONARIO
DELETE FROM TBMEDICAMENTO
DELETE FROM TBREQUISICAO
